### ISSUE TITLE
Fix failed command execution message

### ISSUE THREAD

**Issue by landpro** [gopinath-langote/1build#129]
## Description
`Failed to execute 'mvn clean verify'`

it is not failed to execute
it is that this command was executed and  failed

## Acceptance Criteria
- the message says exactly what happened – e.g. : `Command * failed – execution of the following commands skipped: *`
- Specify `exit-code` of *command* in message

**Comment by gopinath-langote** [comment]
@landpro Do you want to fix this?

**Comment by linonymous** [comment]
Hi There, was wondering if there is any specific reason that we have used '"github.com/codeskyblue/go-sh"' package instead of the already provided "os/exec" package.

**Comment by gopinath-langote** [comment]
Hello @akhilbojedla,

Yes, you are right. Adding exit code is a good idea.
