### ISSUE TITLE
Improve code standard - fix golang linters from codacy

### ISSUE THREAD

**Issue by gopinath-langote** [gopinath-langote/1build#134]
## Description
1build cares a lot about code standards and readability. When we run the simple code standard checks - we found that some things are missing from the language standards, like markdown, golang, etc.

Issues can be found here:
https://app.codacy.com/app/gopinath-langote/1build/issues/index?bid=13534878

From All Patterns section -section below mentioned issue patterns.

This issue will focus on - solving markdown file related topics listed below
1. GoLint_GoLint/Comments/DocComments

## Acceptance Criteria
1. Lint messages with above type should not exist after this PR

## Tech Notes
1. Use appropriate method names - feel free to make method package local if not getting used in another package to avoid unnecessary comments on each method.
2. Feel free ask here, if you have doubt about the method comments

**Comment by RajatVaryani** [comment]
@gopinath-langote Can I sign up for the issue?

**Comment by gopinath-langote** [comment]
@RajatVaryani sure.

Thanks for signup.
