### ISSUE TITLE
Adding Makefile to the project. 

### ISSUE THREAD

**Issue by RajatVaryani** [gopinath-langote/1build#135]
## Description
The issue involves addition of a Makefile to the repository. This will ease the process of Setting up the repository for new contributors. 

## Acceptance Criteria
One I run make,  build, test steps should run and the repository should be ready to contribute to.

**Comment by gopinath-langote** [comment]
Hello @RajatVaryani 
Thank you for opening the issue.


intentionally `Makefile` was not created in project, rather promote contributors to install the `1build` first and run the development command from `1build.yaml` in this project.


Feel free address if something is missing from `Contribution.md` file or `1build.yaml`.

**Comment by RajatVaryani** [comment]
Hello, I am fine with it. But there are few things we can improve. For example the we can have prerequisite for the project which will make the setup process easier. We can also get rid of ```go get -u github.com/golang/dep/cmd/dep
dep ensure``` commands as we don't use dep anymore.

**Comment by gopinath-langote** [comment]
@RajatVaryani You are right.

There are some things to improve in the document.

Your help in updating doc is much appreciated :)
