### ISSUE TITLE
Add --quiet / -q flag to command execution

### ISSUE THREAD

**Issue by gopinath-langote** [gopinath-langote/1build#140]
## Description
Sometimes developers choose to not see all logs/output of your command and just see `success` or `failure` as the outcome. Hence adding `--quite` or `-q` flag to 1build command execution will result in just executing the command but not showing the entire output of it. 

## Acceptance Criteria
- Ability to pass `quiet` or `-q` flag to command execution. 
    ex - ```bash
              1build test --quiet
              1build test -q
             ```
- If flag present - then just print `SUCCESS` (if exit code of the command is `0`) 
- If exit code is not zero - print `FAILURE` with exit code

**Comment by GamerSenior** [comment]
Shouldn't it be --quiet instead of --quite?

**Comment by gopinath-langote** [comment]
@GamerSenior Indeed. updated issue.
Thanks for heads-up

**Comment by anshulxyz** [comment]
Hi Gopinath,

I'd like to work on this issue.

**Comment by gopinath-langote** [comment]
@anshulxyz Sure. go for it.

**Comment by gopinath-langote** [comment]
@anshulxyz I have updated the ACs for the issue. Please revisit them once.

**Comment by anshulxyz** [comment]
@gopinath-langote noted

**Comment by anshulxyz** [comment]
@gopinath-langote is there any style guide or best practices you expect or follow for the repo?

**Comment by gopinath-langote** [comment]
@anshulxyz You do not have any special guidelines yet.

Some automatic checks will happen on each PR - that is it.

While working on code - you will understand the structure.

– In longer run, we should start building guidelines.

**Comment by gopinath-langote** [comment]
@anshulxyz – any progress on the issue - Let me know if you need any help from members!

**Comment by anshulxyz** [comment]
I will work on it, this weekend

**Comment by gopinath-langote** [comment]
Hello @anshulxyz 

Any updates on this?

**Comment by anshulxyz** [comment]
Hi, Gopinath, no updates on this unfortunately.

**Comment by gopinath-langote** [comment]
@anshulxyz I am opening this issue to be picked by anyone - let me know if you get time.

**Comment by ashupatil96** [comment]
@gopinath-langote  can you please assign this to me ?

**Comment by gopinath-langote** [comment]
@ashupatil96 Sure. Go ahead.
