### ISSUE TITLE
Unset multiple command in one go

### ISSUE THREAD

**Issue by gopinath-langote** [gopinath-langote/1build#141]
## Description
Current version support `unset` one command like `1build unset test`. If developer has to remove multiple commands they have to run 1build unset multiple times.

Instead With `1build unset a b c` -> It will be easy to remove three commands in one go. 

## Acceptance Criteria
- Ability to pass multiple commands to `unset`
- `unset` will continue removing next command even after the failure of one
- `unset` will print if any command failed to remove

**Comment by pradeepmurugesan** [comment]
I can work on this..

**Comment by gopinath-langote** [comment]
@pradeepmurugesan sure.

**Comment by boonwj** [comment]
I have created a small PR that implements this functionality. 

Sorry for failing to mention earlier that I was also looking into this :pensive:

**Comment by gopinath-langote** [comment]
Feel free to open PRs. We will review all PRs on same issue.

@boonwj From next time onwards - It will be good if you can comment on the issue that you would like to work :) So that others will not take the same PR.

**Comment by gopinath-langote** [comment]
@boonwj Thanks for the PR.

@pradeepmurugesan You can pick any other ope issue. Sorry for the inconvenience caused.
