### ISSUE TITLE
Version number is not displayed correctly

### ISSUE THREAD

**Issue by boonwj** [gopinath-langote/1build#158]
## Description
The version number within 1build is incorrect. It currently displays 1.1.2 even when it is 1.3.0 now.

Current: 
```console
$ 1build --version
1build version 1.1.2
```

## Acceptance Criteria
`1build --version` should print out the current version number (1.3.0).

**Comment by gopinath-langote** [comment]
@boonwj Thanks for heads-up. Mistakenly, last release wen without changing version number.

I have updated the code to include latest version - next release will have the proper version.

**Comment by boonwj** [comment]
Nice. You work fast here :smile:
