### ISSUE TITLE
[Safe Delete] 1build project configuration by command

### ISSUE THREAD

**Issue by gopinath-langote** [gopinath-langote/1build#167]
## Description
- We want a developer to have the ability to work with 1build - just from the command line (and with 1buil commands)
- Currently, `1build` support init command - which initializes the project configuration
- Same way - we want to have the ability to delete the project configuration
- Ask for consent before deleting the file (If not given by command)
- Ability to pass consent by command itself

## Example
1. `1build delete` - ASK for consent (yes or no)
2. `1build delete --force`
3. `1build delete -f`

## Acceptance Criteria
- `1build delete` / `1build d` -  should ask for consent to delete (y/N)
- The default option will be `N`
- Upon input `n` OR just enter(which by default is NO) - should NOT delete the file.
- Upon input `y` - should delete the file.
- Should not ask for consent (instead, give an error) - If file not present

**Comment by diptag** [comment]
I would like to take this up.
