### ISSUE TITLE
Support interactive commands

### ISSUE THREAD

**Issue by gopinath-langote** [gopinath-langote/1build#193]
## Description

* Currently 1build executes command which providers direct output without user input.
* 1build does not support interactive command yet. Example taking user input, or ssh to remote machine, running repl, running psql etc.

### Example

```bash
1build postgres

Execution plan
--       ----------------------------------------------------------
Phase    Command
--       ----------------------------------------------------------
postgres       pgcli postgres://postgres:password@localhost:5432/postgres


---------------------------------[ pg ]---------------------------------
Warning: Input is not a terminal (fd=0).
Server: PostgreSQL 12.1
Version: 3.0.0
Chat: https://gitter.im/dbcli/pgcli
Home: http://pgcli.com
postgres@localhost:postgres>
Goodbye!

------------------------------------------------------------------------
SUCCESS - Total Time: 00s
------------------------------------------------------------------------
```

> Above command should run the psql ripl & take users command, but 1build doesn't allow to do that.

## Acceptance Criteria

* Support interactive command
* If users inter to interactive session - 1build process will wait for the user to exit and come back to 1build process

**Comment by TimDurward** [comment]
@gopinath-langote this should be a fairly simple implementation.

Currently the the 1build [`bashCommand`](https://github.com/gopinath-langote/1build/blob/master/cmd/exec/exec.go#L97-L99) is expecting [`*sh.Session`](https://github.com/codeskyblue/go-sh/blob/master/sh.go#L44-L60).

```go
func bashCommand(s *sh.Session, command string) *sh.Session {
	return s.Command("bash", "-c", command)
}
```

However we're currently passing in [`*sh.NewSession` ](https://github.com/codeskyblue/go-sh/blob/master/sh.go#L68-L83) to the [`*CommandContext.CommandSession`](CommandSession) when building the [`buildExecutionPlan`](https://github.com/gopinath-langote/1build/blob/master/cmd/exec/exec.go#L67-L95)

The `*sh.NewSession` func is defaulting to an empty string for `Stdin`.
```go
s := &Session{
	inj:    inject.New(),
	alias:  make(map[string][]string),
	dir:    Dir(""),
	Stdin:  strings.NewReader(""),
	Stdout: os.Stdout,
	Stderr: os.Stderr,
	Env:    env,
}
```

We should be able to swap `*sh.NewSession` with their alternative Session func; [`*sh.InteractiveSession`](https://github.com/codeskyblue/go-sh/blob/master/sh.go#L85-L89).
Which uses `*sh.NewSession` but additionally setting Stdin to `SetStdin(os.Stdin)`.

```go
func InteractiveSession() *Session {
	s := NewSession()
	s.SetStdin(os.Stdin)
	return s
}
```


So passing in `sh.InteractiveSession()` to the `*CommandContext.CommandSession` when building the `buildExecutionPlan` should be all we need to add interactive support.

* I tested it out with `docker run nginx -it sh` (to get an interactive shell) and was able to get `1build` to run it interactively.

**Comment by gopinath-langote** [comment]
@TimDurward thanks for doing research on this.

I am curious is there any way we can handle this without the user specifying that it's an interactive command or normal command.

**Comment by gopinath-langote** [comment]
Or setting `s.SetStdin(os.Stdin)` will work for all the usecases?


Could you please and confirm?
