### ISSUE TITLE
Update logo to include moto

### ISSUE THREAD

**Issue by gopinath-langote** [gopinath-langote/1build#81]
- update 1build logo to include moto `Frictionless way of managing project-specific commands`

**Comment by gopinath-langote** [comment]
Ping: @themayurkumbhar

**Comment by themayurkumbhar** [comment]
Yup, sounds cool. 
will start on this. ping you the draft logo updated once done.
will it be `Frictionless way of managing project-specific commands` this line under the logo aligned to bottom center? @gopinath-langote
